'use client';

export async function downloadReceiptPdf(data) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 48;
  let y = margin;

  const receiptNo = String(data.payment?.id || 0).padStart(6, '0');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('PropSync', margin, y);
  y += 28;
  doc.setFontSize(16);
  doc.text('RENT PAYMENT RECEIPT', margin, y);
  y += 22;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Receipt #${receiptNo}`, margin, y);
  y += 30;

  const rows = [
    ['Received from', data.tenant?.full_name || '—'],
    ['Property', data.property?.name || '—'],
    ['Unit', data.unit?.unit_number || '—'],
    ['Payment for', data.paymentMonthLabel || '—'],
    ['Amount', `$${Number(data.payment?.amount_usd || 0).toFixed(2)} USD`],
    ['Payment method', data.paymentMethodLabel || '—'],
    ['Date paid', data.paidDateLabel || '—'],
  ];

  rows.forEach(([label, val]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(val), margin + 140, y);
    y += 22;
  });

  y += 10;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(34, 139, 34);
  doc.text('PAID', margin, y);
  doc.setTextColor(0, 0, 0);
  y += 40;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Owner: ${data.owner?.full_name || ''}`, margin, y);
  y += 30;
  doc.text('Signature: _________________________', margin, y);
  y += 30;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('Thank you for your payment', margin, y);
  y += 14;
  doc.text('Generated by PropSync — Mogadishu Property Management', margin, y);

  const slug = (data.tenant?.full_name || 'tenant').replace(/\s+/g, '-').toLowerCase();
  const month = (data.payment?.payment_month || 'month').replace('-', '');
  doc.save(`receipt-${slug}-${month}.pdf`);
}
